# Generated by Django 4.0.3 on 2024-02-20 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_warnerresponse_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('send', models.BooleanField(default=False)),
            ],
        ),
    ]
